name: Build docker image

on:
  push:
    branches: [ master ]
    #paths:
    #  - 'mysql-backup-s3/*'

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "dark-vex"
          password: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v3
        with:
          context: ./mysql-backup-s3
          file: ./mysql-backup-s3/Dockerfile
          tags: ghcr.io/dark-vex/mysql-backup-s3:latest
          push: true
